CREATE TABLE FESTIVALS (
	ID 		INTEGER 	PRIMARY KEY,
	TYPE 		INTEGER 	NOT NULL,
	FESTIVAL_YEAR 	INTEGER 	NOT NULL,
	POINT 		BOOLEAN,
	JURY 		BOOLEAN,
	TELE 		BOOLEAN
);

CREATE TABLE COUNTRIES (
	ALIAS 		CHAR(2) 	PRIMARY KEY,
	NAME 		VARCHAR(30) 	NOT NULL,
	FLAG_URL 	VARCHAR(40)
);

CREATE TABLE ARTISTS (
	ID 		INTEGER 	PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	NAME 		VARCHAR(30) 	NOT NULL UNIQUE
);

CREATE TABLE SONGS (
	ID		INTEGER		PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	NAME		VARCHAR(40)	NOT NULL,
	ARTIST_ID	INTEGER		NOT NULL,
	FOREIGN KEY (ARTIST_ID) REFERENCES ARTISTS(ID),
	UNIQUE (NAME,ARTIST_ID)
);

CREATE TABLE PARTICIPATIONS (
	FESTIVAL_ID	INTEGER		NOT NULL,
	COUNTRY_ALIAS	CHAR(2)		NOT NULL,
	SONG_ID		INTEGER		NOT NULL,
	FOREIGN KEY (FESTIVAL_ID) REFERENCES FESTIVALS(ID),
	FOREIGN KEY (COUNTRY_ALIAS) REFERENCES COUNTRIES(ALIAS),
	FOREIGN KEY (SONG_ID) REFERENCES SONGS(ID),
	PRIMARY KEY (FESTIVAL_ID,COUNTRY_ALIAS,SONG_ID)
);

CREATE TABLE VOTES (
	FESTIVAL_ID	INTEGER		NOT NULL,
	VOTING_COUNTRY	CHAR(2)		NOT NULL,
	VOTED_COUNTRY	CHAR(2)		NOT NULL,
	JURY_POINTS	INTEGER		NOT NULL,
	TELE_POINTS	INTEGER,
	FOREIGN KEY (FESTIVAL_ID) REFERENCES FESTIVALS(ID),
	FOREIGN KEY (VOTING_COUNTRY) REFERENCES COUNTRIES(ALIAS),
	FOREIGN KEY (VOTED_COUNTRY) REFERENCES COUNTRIES(ALIAS),
	PRIMARY KEY (FESTIVAL_ID, VOTING_COUNTRY, VOTED_COUNTRY),
	CHECK (NOT VOTING_COUNTRY = VOTED_COUNTRY)
);
